# Copyright © 2017 ChaiShushan <chaishushan{AT}gmail.com>.
# License: https://creativecommons.org/licenses/by-nc-sa/4.0/

default:
	go build -o plugin.so -buildmode=plugin plugin.go

clean:
	-rm *.so
