version: '3.1'

services:

  db:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_DATABASE: chat_demo
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypasswd

    networks:
      localnet:
        aliases:
          - mysql-default

  myadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

    networks:
      localnet:
        aliases:
          - mysql-default

networks:
  localnet:
