// Code generated by cmd/cgo; DO NOT EDIT.

//line sum.go:1:1
package main

//int sum(int a, int b);
import _ "unsafe"
//export sum
func sum(a, b  /*line :6:15*/_Ctype_int /*line :6:20*/)  /*line :6:22*/_Ctype_int /*line :6:27*/ {
	return a + b
}

func main(){}

